server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: note-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/notes/**
          
        - id: folder-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/folders/**
        
        - id: sharing-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/sharing/**
        
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
